/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50717
Source Host           : localhost:3306
Source Database       : whatoeat

Target Server Type    : MYSQL
Target Server Version : 50717
File Encoding         : 65001

Date: 2017-04-16 22:40:41
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `dislikelist`
-- ----------------------------
DROP TABLE IF EXISTS `dislikelist`;
CREATE TABLE `dislikelist` (
  `did` int(11) NOT NULL AUTO_INCREMENT,
  `Uid` int(11) DEFAULT NULL,
  `Fid` int(11) DEFAULT NULL,
  PRIMARY KEY (`did`),
  KEY `Uid` (`Uid`),
  KEY `Fid` (`Fid`),
  CONSTRAINT `dislikelist_ibfk_1` FOREIGN KEY (`Uid`) REFERENCES `users` (`Uid`) ON DELETE CASCADE,
  CONSTRAINT `dislikelist_ibfk_2` FOREIGN KEY (`Fid`) REFERENCES `foods` (`Fid`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of dislikelist
-- ----------------------------
INSERT INTO `dislikelist` VALUES ('1', '2', '4');
INSERT INTO `dislikelist` VALUES ('2', '1', '26');
INSERT INTO `dislikelist` VALUES ('3', '1', '25');
INSERT INTO `dislikelist` VALUES ('4', '1', '44');
INSERT INTO `dislikelist` VALUES ('5', '1', '192');

-- ----------------------------
-- Table structure for `foods`
-- ----------------------------
DROP TABLE IF EXISTS `foods`;
CREATE TABLE `foods` (
  `Fid` int(11) NOT NULL AUTO_INCREMENT,
  `FoodName` varchar(20) DEFAULT NULL,
  `FoodType` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`Fid`)
) ENGINE=InnoDB AUTO_INCREMENT=736 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of foods
-- ----------------------------
INSERT INTO `foods` VALUES ('1', '地三鲜', '大荤');
INSERT INTO `foods` VALUES ('2', '干煸牛肉', '大荤');
INSERT INTO `foods` VALUES ('3', '干豆角炒肉', '大荤');
INSERT INTO `foods` VALUES ('4', '宫爆肉丁', '大荤');
INSERT INTO `foods` VALUES ('5', '红烧肉丸', '大荤');
INSERT INTO `foods` VALUES ('6', '京酱肉丝', '大荤');
INSERT INTO `foods` VALUES ('7', '麻辣肉丝', '大荤');
INSERT INTO `foods` VALUES ('8', '梅菜肉饼', '大荤');
INSERT INTO `foods` VALUES ('9', '香菇肉片', '大荤');
INSERT INTO `foods` VALUES ('10', '香芹腊肉', '大荤');
INSERT INTO `foods` VALUES ('11', '香芋烧肉', '大荤');
INSERT INTO `foods` VALUES ('12', '香芋扣肉', '大荤');
INSERT INTO `foods` VALUES ('13', '梅菜扣肉', '大荤');
INSERT INTO `foods` VALUES ('14', '盐煎肉', '大荤');
INSERT INTO `foods` VALUES ('15', '萝卜红烧肉', '大荤');
INSERT INTO `foods` VALUES ('16', '百叶结红烧肉', '大荤');
INSERT INTO `foods` VALUES ('17', '海带结红烧肉', '大荤');
INSERT INTO `foods` VALUES ('18', '包菜回锅肉', '大荤');
INSERT INTO `foods` VALUES ('19', '菜心烩肉圆', '大荤');
INSERT INTO `foods` VALUES ('20', '川味粉蒸肉', '大荤');
INSERT INTO `foods` VALUES ('21', '腐竹红烧肉', '大荤');
INSERT INTO `foods` VALUES ('22', '干煸肉丝', '大荤');
INSERT INTO `foods` VALUES ('23', '咕咾肉', '大荤');
INSERT INTO `foods` VALUES ('24', '广东卤肉', '大荤');
INSERT INTO `foods` VALUES ('25', '红烧大排', '大荤');
INSERT INTO `foods` VALUES ('26', '红烧排骨', '大荤');
INSERT INTO `foods` VALUES ('27', '红烧狮子头', '大荤');
INSERT INTO `foods` VALUES ('28', '红烧猪手', '大荤');
INSERT INTO `foods` VALUES ('29', '尖椒回锅肉', '大荤');
INSERT INTO `foods` VALUES ('30', '茭白红烧肉', '大荤');
INSERT INTO `foods` VALUES ('31', '椒盐排骨', '大荤');
INSERT INTO `foods` VALUES ('32', '椒盐排条', '大荤');
INSERT INTO `foods` VALUES ('33', '京都排条', '大荤');
INSERT INTO `foods` VALUES ('34', '莲藕红烧肉', '大荤');
INSERT INTO `foods` VALUES ('35', '萝卜烧肉', '大荤');
INSERT INTO `foods` VALUES ('36', '毛豆烧肉', '大荤');
INSERT INTO `foods` VALUES ('37', '毛家红烧肉', '大荤');
INSERT INTO `foods` VALUES ('38', '梅菜扣肉', '大荤');
INSERT INTO `foods` VALUES ('39', '梅菜扣猪蹄膀', '大荤');
INSERT INTO `foods` VALUES ('40', '南乳大肉', '大荤');
INSERT INTO `foods` VALUES ('41', '茄汁排条', '大荤');
INSERT INTO `foods` VALUES ('42', '青椒回锅肉', '大荤');
INSERT INTO `foods` VALUES ('43', '清蒸肉排', '大荤');
INSERT INTO `foods` VALUES ('44', '清蒸狮子头', '大荤');
INSERT INTO `foods` VALUES ('45', '三鲜烩肉丸', '大荤');
INSERT INTO `foods` VALUES ('46', '茭白红烧肉', '大荤');
INSERT INTO `foods` VALUES ('47', '四川回锅肉', '大荤');
INSERT INTO `foods` VALUES ('48', '蒜苗回锅肉', '大荤');
INSERT INTO `foods` VALUES ('49', '蒜苔回锅肉', '大荤');
INSERT INTO `foods` VALUES ('50', '蒜香排骨', '大荤');
INSERT INTO `foods` VALUES ('51', '陈皮豉汁蒸排骨', '大荤');
INSERT INTO `foods` VALUES ('52', '坛子焖大肉', '大荤');
INSERT INTO `foods` VALUES ('53', '糖醋排骨', '大荤');
INSERT INTO `foods` VALUES ('54', '土豆红烧肉', '大荤');
INSERT INTO `foods` VALUES ('55', '土豆扣蹄膀', '大荤');
INSERT INTO `foods` VALUES ('56', '莴笋红烧肉', '大荤');
INSERT INTO `foods` VALUES ('57', '莴笋蹄膀', '大荤');
INSERT INTO `foods` VALUES ('58', '咸蛋蒸肉米', '大荤');
INSERT INTO `foods` VALUES ('59', '咸鱼蒸肉米', '大荤');
INSERT INTO `foods` VALUES ('60', '油豆腐红烧肉', '大荤');
INSERT INTO `foods` VALUES ('61', '洋葱回锅肉', '大荤');
INSERT INTO `foods` VALUES ('62', '鱼香肉丝', '大荤');
INSERT INTO `foods` VALUES ('63', '芋艿红烧肉', '大荤');
INSERT INTO `foods` VALUES ('64', '走油肉', '大荤');
INSERT INTO `foods` VALUES ('65', '大头菜炒猪肚', '大荤');
INSERT INTO `foods` VALUES ('66', '白斩鸡', '大荤');
INSERT INTO `foods` VALUES ('67', '葱油鸡翅', '大荤');
INSERT INTO `foods` VALUES ('68', '葱油鸡腿', '大荤');
INSERT INTO `foods` VALUES ('69', '腐竹烧鸡块', '大荤');
INSERT INTO `foods` VALUES ('70', '红烧鸡块', '大荤');
INSERT INTO `foods` VALUES ('71', '椒盐鸡排', '大荤');
INSERT INTO `foods` VALUES ('72', '咖喱鸡块', '大荤');
INSERT INTO `foods` VALUES ('73', '辣烧鸡翅', '大荤');
INSERT INTO `foods` VALUES ('74', '辣烧鸡腿', '大荤');
INSERT INTO `foods` VALUES ('75', '莲藕烧鸡块', '大荤');
INSERT INTO `foods` VALUES ('76', '萝卜烧鸡块', '大荤');
INSERT INTO `foods` VALUES ('77', '茄汁鸡柳', '大荤');
INSERT INTO `foods` VALUES ('78', '青椒地耳炒鸡块', '大荤');
INSERT INTO `foods` VALUES ('79', '土豆烧鸡块', '大荤');
INSERT INTO `foods` VALUES ('80', '莴笋烧鸡块', '大荤');
INSERT INTO `foods` VALUES ('81', '五香土豆鸡块', '大荤');
INSERT INTO `foods` VALUES ('82', '香干烧鸡块', '大荤');
INSERT INTO `foods` VALUES ('83', '香菇烧鸡块', '大荤');
INSERT INTO `foods` VALUES ('84', '香菇蒸滑鸡', '大荤');
INSERT INTO `foods` VALUES ('85', '油炸鸡翅', '大荤');
INSERT INTO `foods` VALUES ('86', '油炸鸡腿', '大荤');
INSERT INTO `foods` VALUES ('87', '芋艿烧鸡块', '大荤');
INSERT INTO `foods` VALUES ('88', '川椒辣子鸡', '大荤');
INSERT INTO `foods` VALUES ('89', '豆豉蒸鸡腿', '大荤');
INSERT INTO `foods` VALUES ('90', '宫爆鸡丁', '大荤');
INSERT INTO `foods` VALUES ('91', '泡椒红油鸡', '大荤');
INSERT INTO `foods` VALUES ('92', '辣仔鸡块*', '大荤');
INSERT INTO `foods` VALUES ('93', '香菇炖鸡', '大荤');
INSERT INTO `foods` VALUES ('94', '孜然辣子鸡', '大荤');
INSERT INTO `foods` VALUES ('95', '辣子鸡丁*', '大荤');
INSERT INTO `foods` VALUES ('96', '莴笋鸡丝', '大荤');
INSERT INTO `foods` VALUES ('97', '酱鸭', '大荤');
INSERT INTO `foods` VALUES ('98', '卤鸭', '大荤');
INSERT INTO `foods` VALUES ('99', '藕块鸭块', '大荤');
INSERT INTO `foods` VALUES ('100', '土豆鸭块', '大荤');
INSERT INTO `foods` VALUES ('101', '啤酒鸭块', '大荤');
INSERT INTO `foods` VALUES ('102', '五香鸭腿', '大荤');
INSERT INTO `foods` VALUES ('103', '香菇鸭块', '大荤');
INSERT INTO `foods` VALUES ('104', '盐水鸭', '大荤');
INSERT INTO `foods` VALUES ('105', '芋艿鸭块', '大荤');
INSERT INTO `foods` VALUES ('106', '竹笋鸭块', '大荤');
INSERT INTO `foods` VALUES ('107', '萝卜烧牛腩', '大荤');
INSERT INTO `foods` VALUES ('108', '藕块烧牛腩', '大荤');
INSERT INTO `foods` VALUES ('109', '山药烧牛腩', '大荤');
INSERT INTO `foods` VALUES ('110', '土豆烧牛腩', '大荤');
INSERT INTO `foods` VALUES ('111', '五香牛腩', '大荤');
INSERT INTO `foods` VALUES ('112', '辣味鱼', '大荤');
INSERT INTO `foods` VALUES ('113', '酸菜鱼', '大荤');
INSERT INTO `foods` VALUES ('114', '香辣鱼块', '大荤');
INSERT INTO `foods` VALUES ('115', '豉汁蒸鱼块', '大荤');
INSERT INTO `foods` VALUES ('116', '豆腐烧鱼', '大荤');
INSERT INTO `foods` VALUES ('117', '剁椒鲢鱼块', '大荤');
INSERT INTO `foods` VALUES ('118', '剁椒鲢鱼头', '大荤');
INSERT INTO `foods` VALUES ('119', '剁椒蒸鱼块', '大荤');
INSERT INTO `foods` VALUES ('120', '干烧福寿鱼', '大荤');
INSERT INTO `foods` VALUES ('121', '干烧鱼块', '大荤');
INSERT INTO `foods` VALUES ('122', '红烧鲢鱼块', '大荤');
INSERT INTO `foods` VALUES ('123', '红烧鱼块', '大荤');
INSERT INTO `foods` VALUES ('124', '剁椒带鱼', '大荤');
INSERT INTO `foods` VALUES ('125', '红烧带鱼', '大荤');
INSERT INTO `foods` VALUES ('126', '红烧小黄鱼', '大荤');
INSERT INTO `foods` VALUES ('127', '椒盐小黄鱼', '大荤');
INSERT INTO `foods` VALUES ('128', '辣烧带鱼', '大荤');
INSERT INTO `foods` VALUES ('129', '辣烧小黄鱼', '大荤');
INSERT INTO `foods` VALUES ('130', '面拖带鱼', '大荤');
INSERT INTO `foods` VALUES ('131', '清蒸带鱼', '大荤');
INSERT INTO `foods` VALUES ('132', '蒜香带鱼', '大荤');
INSERT INTO `foods` VALUES ('133', '蒜香小黄鱼', '大荤');
INSERT INTO `foods` VALUES ('134', '雪菜小黄鱼', '大荤');
INSERT INTO `foods` VALUES ('135', '本芹炒方腿', '小荤');
INSERT INTO `foods` VALUES ('136', '本芹炒腊肉', '小荤');
INSERT INTO `foods` VALUES ('137', '本芹炒肉丝', '小荤');
INSERT INTO `foods` VALUES ('138', '本芹炒猪肝', '小荤');
INSERT INTO `foods` VALUES ('139', '菜花肉片', '小荤');
INSERT INTO `foods` VALUES ('140', '菜心烩肉丸', '小荤');
INSERT INTO `foods` VALUES ('141', '川椒回锅肉', '小荤');
INSERT INTO `foods` VALUES ('142', '大头菜炒方腿', '小荤');
INSERT INTO `foods` VALUES ('143', '大头菜炒腊肉', '小荤');
INSERT INTO `foods` VALUES ('144', '大头菜炒肉丝', '小荤');
INSERT INTO `foods` VALUES ('145', '大头菜炒猪肝', '小荤');
INSERT INTO `foods` VALUES ('146', '四季豆肉丁', '小荤');
INSERT INTO `foods` VALUES ('147', '地瓜炒肉丝', '小荤');
INSERT INTO `foods` VALUES ('148', '地瓜肉丁', '小荤');
INSERT INTO `foods` VALUES ('149', '豆角炒肉丝', '小荤');
INSERT INTO `foods` VALUES ('150', '佛手瓜炒肉', '小荤');
INSERT INTO `foods` VALUES ('151', '腐竹肉片', '小荤');
INSERT INTO `foods` VALUES ('152', '干笋肉丝', '小荤');
INSERT INTO `foods` VALUES ('153', '宫爆肉丁', '小荤');
INSERT INTO `foods` VALUES ('154', '海带肉丝', '小荤');
INSERT INTO `foods` VALUES ('155', '荷兰豆炒肉片', '小荤');
INSERT INTO `foods` VALUES ('156', '红椒香干肉丝', '小荤');
INSERT INTO `foods` VALUES ('157', '花菜炒肉片', '小荤');
INSERT INTO `foods` VALUES ('158', '花菜木耳肉片', '小荤');
INSERT INTO `foods` VALUES ('159', '黄瓜炒肉片', '小荤');
INSERT INTO `foods` VALUES ('160', '家常豆腐', '小荤');
INSERT INTO `foods` VALUES ('161', '尖椒炒腊肉', '小荤');
INSERT INTO `foods` VALUES ('162', '尖椒肉丝', '小荤');
INSERT INTO `foods` VALUES ('163', '豇豆炒方腿', '小荤');
INSERT INTO `foods` VALUES ('164', '豇豆炒腊肉', '小荤');
INSERT INTO `foods` VALUES ('165', '豇豆炒肉丝', '小荤');
INSERT INTO `foods` VALUES ('166', '豇豆肉丁', '小荤');
INSERT INTO `foods` VALUES ('167', '酱爆肉', '小荤');
INSERT INTO `foods` VALUES ('168', '酱干炒方腿', '小荤');
INSERT INTO `foods` VALUES ('169', '茭白炒肉片', '小荤');
INSERT INTO `foods` VALUES ('170', '京酱肉丝', '小荤');
INSERT INTO `foods` VALUES ('171', '京酱土豆肉丁', '小荤');
INSERT INTO `foods` VALUES ('172', '韭菜炒肉丝', '小荤');
INSERT INTO `foods` VALUES ('173', '韭黄炒肉丝', '小荤');
INSERT INTO `foods` VALUES ('174', '卷心菜炒肉片', '小荤');
INSERT INTO `foods` VALUES ('175', '卷心菜回锅肉', '小荤');
INSERT INTO `foods` VALUES ('176', '兰花炒肉片', '小荤');
INSERT INTO `foods` VALUES ('177', '凉瓜炒肉', '小荤');
INSERT INTO `foods` VALUES ('178', '萝卜炒方腿', '小荤');
INSERT INTO `foods` VALUES ('179', '萝卜炒腊肉', '小荤');
INSERT INTO `foods` VALUES ('180', '萝卜炒肉丝', '小荤');
INSERT INTO `foods` VALUES ('181', '萝卜毛豆炒肉丝', '小荤');
INSERT INTO `foods` VALUES ('182', '萝卜红烧肉', '小荤');
INSERT INTO `foods` VALUES ('183', '萝卜干炒肉丝', '小荤');
INSERT INTO `foods` VALUES ('184', '麻婆豆腐', '小荤');
INSERT INTO `foods` VALUES ('185', '炒木须肉', '小荤');
INSERT INTO `foods` VALUES ('186', '木耳花菜肉片', '小荤');
INSERT INTO `foods` VALUES ('187', '木耳肉丝', '小荤');
INSERT INTO `foods` VALUES ('188', '藕丁肉丁', '小荤');
INSERT INTO `foods` VALUES ('189', '平菇青椒炒肉片', '小荤');
INSERT INTO `foods` VALUES ('190', '青瓜腊肉', '小荤');
INSERT INTO `foods` VALUES ('191', '青椒炒方腿', '小荤');
INSERT INTO `foods` VALUES ('192', '青椒炒腊肉', '小荤');
INSERT INTO `foods` VALUES ('193', '青椒炒肉片', '小荤');
INSERT INTO `foods` VALUES ('194', '青椒酱干肉丁', '小荤');
INSERT INTO `foods` VALUES ('195', '青椒茭白肉丁', '小荤');
INSERT INTO `foods` VALUES ('196', '青椒木耳炒肉片', '小荤');
INSERT INTO `foods` VALUES ('197', '青椒木耳肉丝', '小荤');
INSERT INTO `foods` VALUES ('198', '青椒牛肉', '小荤');
INSERT INTO `foods` VALUES ('199', '青椒肉丁', '小荤');
INSERT INTO `foods` VALUES ('200', '青笋肉片', '小荤');
INSERT INTO `foods` VALUES ('201', '青笋香菇肉丝', '小荤');
INSERT INTO `foods` VALUES ('202', '肉米豆腐', '小荤');
INSERT INTO `foods` VALUES ('203', '肉米茄子', '小荤');
INSERT INTO `foods` VALUES ('204', '肉末豆腐', '小荤');
INSERT INTO `foods` VALUES ('205', '肉末粉丝', '小荤');
INSERT INTO `foods` VALUES ('206', '肉末粉条', '小荤');
INSERT INTO `foods` VALUES ('207', '肉末海带丝', '小荤');
INSERT INTO `foods` VALUES ('208', '肉末茄子', '小荤');
INSERT INTO `foods` VALUES ('209', '肉末日本豆腐', '小荤');
INSERT INTO `foods` VALUES ('210', '肉末油豆腐', '小荤');
INSERT INTO `foods` VALUES ('211', '肉末油面筋', '小荤');
INSERT INTO `foods` VALUES ('212', '三色肉丁', '小荤');
INSERT INTO `foods` VALUES ('213', '山药木耳炒肉片', '小荤');
INSERT INTO `foods` VALUES ('214', '什锦菜炒方腿', '小荤');
INSERT INTO `foods` VALUES ('215', '什锦菜炒腊肉', '小荤');
INSERT INTO `foods` VALUES ('216', '什锦菜炒肉丝', '小荤');
INSERT INTO `foods` VALUES ('217', '双卜肉丁', '小荤');
INSERT INTO `foods` VALUES ('218', '水煮肉片', '小荤');
INSERT INTO `foods` VALUES ('219', '四季豆炒肉丝*', '小荤');
INSERT INTO `foods` VALUES ('220', '酸菜回锅肉*', '小荤');
INSERT INTO `foods` VALUES ('221', '酸豆角炒肉末', '小荤');
INSERT INTO `foods` VALUES ('222', '酸豇豆炒方腿', '小荤');
INSERT INTO `foods` VALUES ('223', '酸豇豆炒腊肉', '小荤');
INSERT INTO `foods` VALUES ('224', '酸豇豆炒肉丝', '小荤');
INSERT INTO `foods` VALUES ('225', '蒜苗炒腊肉', '小荤');
INSERT INTO `foods` VALUES ('226', '蒜苔炒肉丝', '小荤');
INSERT INTO `foods` VALUES ('227', '土豆炒方腿', '小荤');
INSERT INTO `foods` VALUES ('228', '土豆炒腊肉', '小荤');
INSERT INTO `foods` VALUES ('229', '土豆炒肉丝', '小荤');
INSERT INTO `foods` VALUES ('230', '莴笋炒方腿', '小荤');
INSERT INTO `foods` VALUES ('231', '莴笋炒腊肉', '小荤');
INSERT INTO `foods` VALUES ('232', '莴笋炒肉片', '小荤');
INSERT INTO `foods` VALUES ('233', '莴笋炒肉丝', '小荤');
INSERT INTO `foods` VALUES ('234', '莴笋肉丁', '小荤');
INSERT INTO `foods` VALUES ('235', '西葫芦炒肉片', '小荤');
INSERT INTO `foods` VALUES ('236', '西兰花炒肉片', '小荤');
INSERT INTO `foods` VALUES ('237', '西芹炒方腿', '小荤');
INSERT INTO `foods` VALUES ('238', '西芹炒腊肉*', '小荤');
INSERT INTO `foods` VALUES ('239', '西芹炒肉片', '小荤');
INSERT INTO `foods` VALUES ('240', '西芹炒肉丝', '小荤');
INSERT INTO `foods` VALUES ('241', '西芹肉丁', '小荤');
INSERT INTO `foods` VALUES ('242', '咸菜炒肉丝', '小荤');
INSERT INTO `foods` VALUES ('243', '香干炒肉丝', '小荤');
INSERT INTO `foods` VALUES ('244', '香干红椒肉丝', '小荤');
INSERT INTO `foods` VALUES ('245', '香菇青菜炒肉片', '小荤');
INSERT INTO `foods` VALUES ('246', '香菇青椒炒肉片*', '小荤');
INSERT INTO `foods` VALUES ('247', '香芹炒肉', '小荤');
INSERT INTO `foods` VALUES ('248', '香芹肉丝', '小荤');
INSERT INTO `foods` VALUES ('249', '洋葱炒肉片', '小荤');
INSERT INTO `foods` VALUES ('250', '腰豆肉丁', '小荤');
INSERT INTO `foods` VALUES ('251', '油面筋塞肉', '小荤');
INSERT INTO `foods` VALUES ('252', '油三角塞肉', '小荤');
INSERT INTO `foods` VALUES ('253', '鱼香肉丝', '小荤');
INSERT INTO `foods` VALUES ('254', '榨菜炒方腿', '小荤');
INSERT INTO `foods` VALUES ('255', '榨菜炒肉丝', '小荤');
INSERT INTO `foods` VALUES ('256', '紫包菜炒肉片', '小荤');
INSERT INTO `foods` VALUES ('257', '咸鸭蛋', '小荤');
INSERT INTO `foods` VALUES ('258', '本芹炒鸡丝', '小荤');
INSERT INTO `foods` VALUES ('259', '春笋炒鸡片', '小荤');
INSERT INTO `foods` VALUES ('260', '大头菜炒鸡丝', '小荤');
INSERT INTO `foods` VALUES ('261', '四季豆鸡丁', '小荤');
INSERT INTO `foods` VALUES ('262', '地瓜炒鸡丝', '小荤');
INSERT INTO `foods` VALUES ('263', '地瓜鸡丁', '小荤');
INSERT INTO `foods` VALUES ('264', '佛手瓜炒鸡片', '小荤');
INSERT INTO `foods` VALUES ('265', '宫爆鸡丁', '小荤');
INSERT INTO `foods` VALUES ('266', '海带丝炒鸡丝', '小荤');
INSERT INTO `foods` VALUES ('267', '荷兰豆炒鸡片', '小荤');
INSERT INTO `foods` VALUES ('268', '花菜炒鸡片', '小荤');
INSERT INTO `foods` VALUES ('269', '黄瓜炒鸡片', '小荤');
INSERT INTO `foods` VALUES ('270', '豇豆炒鸡丝', '小荤');
INSERT INTO `foods` VALUES ('271', '豇豆鸡丁', '小荤');
INSERT INTO `foods` VALUES ('272', '茭白炒鸡片', '小荤');
INSERT INTO `foods` VALUES ('273', '京酱土豆鸡丁', '小荤');
INSERT INTO `foods` VALUES ('274', '韭菜炒鸡丝', '小荤');
INSERT INTO `foods` VALUES ('275', '韭黄炒鸡丝', '小荤');
INSERT INTO `foods` VALUES ('276', '卷心菜炒鸡片', '小荤');
INSERT INTO `foods` VALUES ('277', '藕丁鸡丁', '小荤');
INSERT INTO `foods` VALUES ('278', '平菇青椒炒鸡片', '小荤');
INSERT INTO `foods` VALUES ('279', '青椒炒鸡片', '小荤');
INSERT INTO `foods` VALUES ('280', '青椒炒鸡丝', '小荤');
INSERT INTO `foods` VALUES ('281', '青椒鸡丁', '小荤');
INSERT INTO `foods` VALUES ('282', '青椒酱干鸡丁', '小荤');
INSERT INTO `foods` VALUES ('283', '青椒茭白鸡丁', '小荤');
INSERT INTO `foods` VALUES ('284', '青椒木耳炒鸡片', '小荤');
INSERT INTO `foods` VALUES ('285', '青雪菜炒鸡丝', '小荤');
INSERT INTO `foods` VALUES ('286', '青雪菜毛豆炒鸡丝', '小荤');
INSERT INTO `foods` VALUES ('287', '山药木耳炒鸡片', '小荤');
INSERT INTO `foods` VALUES ('288', '什锦菜炒鸡丝', '小荤');
INSERT INTO `foods` VALUES ('289', '双卜鸡丁', '小荤');
INSERT INTO `foods` VALUES ('290', '酸豇豆炒鸡丝', '小荤');
INSERT INTO `foods` VALUES ('291', '蒜苔炒鸡丝*', '小荤');
INSERT INTO `foods` VALUES ('292', '土豆炒鸡片', '小荤');
INSERT INTO `foods` VALUES ('293', '土豆炒鸡丝', '小荤');
INSERT INTO `foods` VALUES ('294', '土豆鸡丁', '小荤');
INSERT INTO `foods` VALUES ('295', '莴笋炒鸡片', '小荤');
INSERT INTO `foods` VALUES ('296', '莴笋炒鸡丝', '小荤');
INSERT INTO `foods` VALUES ('297', '莴笋鸡丁', '小荤');
INSERT INTO `foods` VALUES ('298', '五彩鸡丝', '小荤');
INSERT INTO `foods` VALUES ('299', '西红柿炒蛋', '小荤');
INSERT INTO `foods` VALUES ('300', '西兰花炒鸡片', '小荤');
INSERT INTO `foods` VALUES ('301', '西芹炒鸡片', '小荤');
INSERT INTO `foods` VALUES ('302', '西芹炒鸡丝', '小荤');
INSERT INTO `foods` VALUES ('303', '西芹鸡丁', '小荤');
INSERT INTO `foods` VALUES ('304', '香干炒鸡丝', '小荤');
INSERT INTO `foods` VALUES ('305', '香菇青菜炒鸡片', '小荤');
INSERT INTO `foods` VALUES ('306', '香辣鸡片', '小荤');
INSERT INTO `foods` VALUES ('307', '洋葱炒鸡片', '小荤');
INSERT INTO `foods` VALUES ('308', '本芹炒蛋', '小荤');
INSERT INTO `foods` VALUES ('309', '大头菜炒蛋', '小荤');
INSERT INTO `foods` VALUES ('310', '番茄炒蛋', '小荤');
INSERT INTO `foods` VALUES ('311', '方腿炒蛋', '小荤');
INSERT INTO `foods` VALUES ('312', '佛手瓜炒蛋', '小荤');
INSERT INTO `foods` VALUES ('313', '荷包蛋', '小荤');
INSERT INTO `foods` VALUES ('314', '黄瓜炒蛋', '小荤');
INSERT INTO `foods` VALUES ('315', '酱蛋', '小荤');
INSERT INTO `foods` VALUES ('316', '京葱炒蛋', '小荤');
INSERT INTO `foods` VALUES ('317', '韭菜炒蛋', '小荤');
INSERT INTO `foods` VALUES ('318', '苦瓜炒蛋', '小荤');
INSERT INTO `foods` VALUES ('319', '卤蛋', '小荤');
INSERT INTO `foods` VALUES ('320', '木须炒蛋', '小荤');
INSERT INTO `foods` VALUES ('321', '皮蛋豆腐', '小荤');
INSERT INTO `foods` VALUES ('322', '青瓜炒蛋', '小荤');
INSERT INTO `foods` VALUES ('323', '青椒炒蛋', '小荤');
INSERT INTO `foods` VALUES ('324', '莴笋炒蛋', '小荤');
INSERT INTO `foods` VALUES ('325', '西芹炒蛋', '小荤');
INSERT INTO `foods` VALUES ('326', '洋葱炒蛋', '小荤');
INSERT INTO `foods` VALUES ('327', '榨菜炒蛋', '小荤');
INSERT INTO `foods` VALUES ('328', '肉末豆角', '小荤');
INSERT INTO `foods` VALUES ('329', '鱼香茄子', '小荤');
INSERT INTO `foods` VALUES ('330', '肉末茄子', '小荤');
INSERT INTO `foods` VALUES ('331', '肉茸冬瓜', '小荤');
INSERT INTO `foods` VALUES ('332', '肉末烧南瓜', '小荤');
INSERT INTO `foods` VALUES ('333', '炸萝卜丸子', '小荤');
INSERT INTO `foods` VALUES ('334', '肉末咸菜', '小荤');
INSERT INTO `foods` VALUES ('335', '碎米鸡丁', '小荤');
INSERT INTO `foods` VALUES ('336', '香辣鸡丁', '小荤');
INSERT INTO `foods` VALUES ('337', '拌鸡丝', '小荤');
INSERT INTO `foods` VALUES ('338', '辣子鸡丁', '小荤');
INSERT INTO `foods` VALUES ('339', '青笋烧鸡', '小荤');
INSERT INTO `foods` VALUES ('340', '五彩鸡丁', '小荤');
INSERT INTO `foods` VALUES ('341', '洋葱鸡片', '小荤');
INSERT INTO `foods` VALUES ('342', '洋葱鸡杂', '小荤');
INSERT INTO `foods` VALUES ('343', '菜花鸡片', '小荤');
INSERT INTO `foods` VALUES ('344', '水笋鸡片', '小荤');
INSERT INTO `foods` VALUES ('345', '西芹鸡片', '小荤');
INSERT INTO `foods` VALUES ('346', '豆角鸡珍', '小荤');
INSERT INTO `foods` VALUES ('347', '五彩鸡片', '小荤');
INSERT INTO `foods` VALUES ('348', '青椒木耳鸡片', '小荤');
INSERT INTO `foods` VALUES ('349', '青笋鸡片', '小荤');
INSERT INTO `foods` VALUES ('350', '西芹鸡丁', '小荤');
INSERT INTO `foods` VALUES ('351', '酸辣鸡丁', '小荤');
INSERT INTO `foods` VALUES ('352', '宫爆鸡丁', '小荤');
INSERT INTO `foods` VALUES ('353', '丝瓜鸡片', '小荤');
INSERT INTO `foods` VALUES ('354', '青椒鸡片', '小荤');
INSERT INTO `foods` VALUES ('355', '苦瓜鸡片', '小荤');
INSERT INTO `foods` VALUES ('356', '五彩鸡片', '小荤');
INSERT INTO `foods` VALUES ('357', '炒木须肉', '小荤');
INSERT INTO `foods` VALUES ('358', '韭黄炒蛋', '小荤');
INSERT INTO `foods` VALUES ('359', '榨菜炒蛋', '小荤');
INSERT INTO `foods` VALUES ('360', '萝卜干炒蛋', '小荤');
INSERT INTO `foods` VALUES ('361', '西红柿炒蛋', '小荤');
INSERT INTO `foods` VALUES ('362', '苦瓜炒蛋', '小荤');
INSERT INTO `foods` VALUES ('363', '木耳炒蛋', '小荤');
INSERT INTO `foods` VALUES ('364', '葱花炒蛋', '小荤');
INSERT INTO `foods` VALUES ('365', '韭菜炒蛋', '小荤');
INSERT INTO `foods` VALUES ('366', '五柳炒蛋', '小荤');
INSERT INTO `foods` VALUES ('367', '兰豆炒腊肠', '大荤');
INSERT INTO `foods` VALUES ('368', '腊肉', '大荤');
INSERT INTO `foods` VALUES ('369', '糖醋猪扒', '大荤');
INSERT INTO `foods` VALUES ('370', '酱爆肉', '大荤');
INSERT INTO `foods` VALUES ('371', '卤排骨', '大荤');
INSERT INTO `foods` VALUES ('372', '糖醋排骨', '大荤');
INSERT INTO `foods` VALUES ('373', '盐煎肉', '大荤');
INSERT INTO `foods` VALUES ('374', '红烧肉', '大荤');
INSERT INTO `foods` VALUES ('375', '黄豆排骨', '大荤');
INSERT INTO `foods` VALUES ('376', '蒜泥白肉', '大荤');
INSERT INTO `foods` VALUES ('377', '麻辣牛肉', '大荤');
INSERT INTO `foods` VALUES ('378', '腊肠', '大荤');
INSERT INTO `foods` VALUES ('379', '双冬排骨', '大荤');
INSERT INTO `foods` VALUES ('380', '苦瓜炖排骨', '大荤');
INSERT INTO `foods` VALUES ('381', '椒盐排骨', '大荤');
INSERT INTO `foods` VALUES ('382', '五香排骨', '大荤');
INSERT INTO `foods` VALUES ('383', '卤猪手', '大荤');
INSERT INTO `foods` VALUES ('384', '椒盐密肉', '大荤');
INSERT INTO `foods` VALUES ('385', '京都猪扒', '大荤');
INSERT INTO `foods` VALUES ('386', '红焖猪头皮', '大荤');
INSERT INTO `foods` VALUES ('387', '苦瓜焖肉', '大荤');
INSERT INTO `foods` VALUES ('388', '拌猪头皮', '大荤');
INSERT INTO `foods` VALUES ('389', '香糟肉', '大荤');
INSERT INTO `foods` VALUES ('390', '干煸肉丝', '大荤');
INSERT INTO `foods` VALUES ('391', '五香肉', '大荤');
INSERT INTO `foods` VALUES ('392', '椒盐猪扒', '大荤');
INSERT INTO `foods` VALUES ('393', '豉汁排骨', '大荤');
INSERT INTO `foods` VALUES ('394', '卤水肘子', '大荤');
INSERT INTO `foods` VALUES ('395', '咕噜肉', '大荤');
INSERT INTO `foods` VALUES ('396', '萝卜炖排骨', '大荤');
INSERT INTO `foods` VALUES ('397', '卤五花肉', '大荤');
INSERT INTO `foods` VALUES ('398', '芽菜肉丝', '大荤');
INSERT INTO `foods` VALUES ('399', '卤肉', '大荤');
INSERT INTO `foods` VALUES ('400', '红烧排骨', '大荤');
INSERT INTO `foods` VALUES ('401', '酱爆里脊', '大荤');
INSERT INTO `foods` VALUES ('402', '水晶肘子', '大荤');
INSERT INTO `foods` VALUES ('403', '粉蒸肉', '大荤');
INSERT INTO `foods` VALUES ('404', '南乳猪手', '大荤');
INSERT INTO `foods` VALUES ('405', '香芋排骨', '大荤');
INSERT INTO `foods` VALUES ('406', '炸肉卷', '大荤');
INSERT INTO `foods` VALUES ('407', '黑椒猪扒', '大荤');
INSERT INTO `foods` VALUES ('408', '珍珠肉丸', '大荤');
INSERT INTO `foods` VALUES ('409', '陈皮肉卷', '大荤');
INSERT INTO `foods` VALUES ('410', '白云猪手', '大荤');
INSERT INTO `foods` VALUES ('411', '南乳叉烧', '大荤');
INSERT INTO `foods` VALUES ('412', '芝麻排骨', '大荤');
INSERT INTO `foods` VALUES ('413', '京酱肉丝', '大荤');
INSERT INTO `foods` VALUES ('414', '扣排骨', '大荤');
INSERT INTO `foods` VALUES ('415', '鱼香肉花', '大荤');
INSERT INTO `foods` VALUES ('416', '玉兰炒肉花', '大荤');
INSERT INTO `foods` VALUES ('417', '咸烧白', '大荤');
INSERT INTO `foods` VALUES ('418', '梅菜扣肉', '大荤');
INSERT INTO `foods` VALUES ('419', '萝卜肉丸', '大荤');
INSERT INTO `foods` VALUES ('420', '香芋扣肉', '大荤');
INSERT INTO `foods` VALUES ('421', '土豆肉方', '大荤');
INSERT INTO `foods` VALUES ('422', '脆炸火腿', '大荤');
INSERT INTO `foods` VALUES ('423', '梅菜肉方', '大荤');
INSERT INTO `foods` VALUES ('424', '炸热狗肠', '大荤');
INSERT INTO `foods` VALUES ('425', '梅菜肉饼', '大荤');
INSERT INTO `foods` VALUES ('426', '青豆米烧肉', '大荤');
INSERT INTO `foods` VALUES ('427', '洋葱腊肉', '大荤');
INSERT INTO `foods` VALUES ('428', '兰豆炒肉片', '大荤');
INSERT INTO `foods` VALUES ('429', '兰豆炒腊肉', '大荤');
INSERT INTO `foods` VALUES ('430', '西芹炒腊肠', '大荤');
INSERT INTO `foods` VALUES ('431', '酿苦瓜', '大荤');
INSERT INTO `foods` VALUES ('432', '子姜肉片', '大荤');
INSERT INTO `foods` VALUES ('433', '玉豆肉片', '大荤');
INSERT INTO `foods` VALUES ('434', '蒜苗回锅肉', '大荤');
INSERT INTO `foods` VALUES ('435', '菠萝肉片', '大荤');
INSERT INTO `foods` VALUES ('436', '草菇肉片', '大荤');
INSERT INTO `foods` VALUES ('437', '笋干炒肉片', '大荤');
INSERT INTO `foods` VALUES ('438', '青椒腊肉', '大荤');
INSERT INTO `foods` VALUES ('439', '肥肉蒸咸鱼', '大荤');
INSERT INTO `foods` VALUES ('440', '西芹腊肉', '大荤');
INSERT INTO `foods` VALUES ('441', '蒜苔腊肉', '大荤');
INSERT INTO `foods` VALUES ('442', '西兰花肉片', '大荤');
INSERT INTO `foods` VALUES ('443', '平菇肉片', '大荤');
INSERT INTO `foods` VALUES ('444', '桂花皮冻', '大荤');
INSERT INTO `foods` VALUES ('445', '酿豆腐', '大荤');
INSERT INTO `foods` VALUES ('446', '脆炸椒盒', '大荤');
INSERT INTO `foods` VALUES ('447', '鱼香茄饼', '大荤');
INSERT INTO `foods` VALUES ('448', '脆炸茄夹', '大荤');
INSERT INTO `foods` VALUES ('449', '鲜菇肉片', '大荤');
INSERT INTO `foods` VALUES ('450', '蘑菇肉片', '大荤');
INSERT INTO `foods` VALUES ('451', '鲜笋烧肉', '大荤');
INSERT INTO `foods` VALUES ('452', '竹笋肉片', '大荤');
INSERT INTO `foods` VALUES ('453', '笋干烧肉', '大荤');
INSERT INTO `foods` VALUES ('454', '麻辣猪肚', '大荤');
INSERT INTO `foods` VALUES ('455', '拌猪肝', '大荤');
INSERT INTO `foods` VALUES ('456', '尖椒肚丝', '大荤');
INSERT INTO `foods` VALUES ('457', '拌猪肚', '大荤');
INSERT INTO `foods` VALUES ('458', '红油猪舌', '大荤');
INSERT INTO `foods` VALUES ('459', '麻辣牛肚', '大荤');
INSERT INTO `foods` VALUES ('460', '五香猪耳', '大荤');
INSERT INTO `foods` VALUES ('461', '红烧肚条', '大荤');
INSERT INTO `foods` VALUES ('462', '凉拌猪耳', '大荤');
INSERT INTO `foods` VALUES ('463', '拌猪利', '大荤');
INSERT INTO `foods` VALUES ('464', '红油牛柏叶', '大荤');
INSERT INTO `foods` VALUES ('465', '酱爆猪肝', '大荤');
INSERT INTO `foods` VALUES ('466', '红油猪耳', '大荤');
INSERT INTO `foods` VALUES ('467', '红油猪肚', '大荤');
INSERT INTO `foods` VALUES ('468', '红烧肥肠', '大荤');
INSERT INTO `foods` VALUES ('469', '五香猪舌', '大荤');
INSERT INTO `foods` VALUES ('470', '卤猪肝', '大荤');
INSERT INTO `foods` VALUES ('471', '五香猪肝', '大荤');
INSERT INTO `foods` VALUES ('472', '熘肝尖', '大荤');
INSERT INTO `foods` VALUES ('473', '洋葱爆牛肚', '大荤');
INSERT INTO `foods` VALUES ('474', '姜葱爆猪肚', '大荤');
INSERT INTO `foods` VALUES ('475', '咸菜猪肚', '大荤');
INSERT INTO `foods` VALUES ('476', '尖椒猪肚', '大荤');
INSERT INTO `foods` VALUES ('477', '尖椒牛肚', '大荤');
INSERT INTO `foods` VALUES ('478', '鱼香猪肝', '大荤');
INSERT INTO `foods` VALUES ('479', '酱爆猪肝', '大荤');
INSERT INTO `foods` VALUES ('480', '尖椒猪肚', '大荤');
INSERT INTO `foods` VALUES ('481', '尖椒牛肚', '大荤');
INSERT INTO `foods` VALUES ('482', '咸菜猪肝', '大荤');
INSERT INTO `foods` VALUES ('483', '青笋猪肝', '大荤');
INSERT INTO `foods` VALUES ('484', '大葱猪肝', '大荤');
INSERT INTO `foods` VALUES ('485', '蒜苔猪肝', '大荤');
INSERT INTO `foods` VALUES ('486', '洋葱猪肝', '大荤');
INSERT INTO `foods` VALUES ('487', '尖椒猪肝', '大荤');
INSERT INTO `foods` VALUES ('488', '西芹猪肝', '大荤');
INSERT INTO `foods` VALUES ('489', '清炖羊肉', '大荤');
INSERT INTO `foods` VALUES ('490', '孜然羊肉', '大荤');
INSERT INTO `foods` VALUES ('491', '尖椒羊肉', '大荤');
INSERT INTO `foods` VALUES ('492', '西芹炒羊肉', '大荤');
INSERT INTO `foods` VALUES ('493', '啤酒鸭', '大荤');
INSERT INTO `foods` VALUES ('494', '卤水鸭', '大荤');
INSERT INTO `foods` VALUES ('495', '红烧鸭块', '大荤');
INSERT INTO `foods` VALUES ('496', '紫菜扒鸭', '大荤');
INSERT INTO `foods` VALUES ('497', '烫皮鸭', '大荤');
INSERT INTO `foods` VALUES ('498', '豉汁扣鸭', '大荤');
INSERT INTO `foods` VALUES ('499', '蚝油鸭', '大荤');
INSERT INTO `foods` VALUES ('500', '陈皮焖鸭', '大荤');
INSERT INTO `foods` VALUES ('501', '腊鸭', '大荤');
INSERT INTO `foods` VALUES ('502', '冬菇扒鸭', '大荤');
INSERT INTO `foods` VALUES ('503', '魔芋烧鸭', '大荤');
INSERT INTO `foods` VALUES ('504', '板鸭', '大荤');
INSERT INTO `foods` VALUES ('505', '油淋仔鸭', '大荤');
INSERT INTO `foods` VALUES ('506', '樟茶鸭子', '大荤');
INSERT INTO `foods` VALUES ('507', '洋葱炒鸭什', '大荤');
INSERT INTO `foods` VALUES ('508', '洋葱牛肉', '大荤');
INSERT INTO `foods` VALUES ('509', '五香牛肉', '大荤');
INSERT INTO `foods` VALUES ('510', '卤牛肉', '大荤');
INSERT INTO `foods` VALUES ('511', '三色烩牛肉', '大荤');
INSERT INTO `foods` VALUES ('512', '黑椒牛扒', '大荤');
INSERT INTO `foods` VALUES ('513', '五香牛腩', '大荤');
INSERT INTO `foods` VALUES ('514', '麻辣牛肉丝', '大荤');
INSERT INTO `foods` VALUES ('515', '干煸牛肉', '大荤');
INSERT INTO `foods` VALUES ('516', '红烧牛肉丸', '大荤');
INSERT INTO `foods` VALUES ('517', '水煮牛肉', '大荤');
INSERT INTO `foods` VALUES ('518', '清蒸牛肉丸', '大荤');
INSERT INTO `foods` VALUES ('519', '卤牛肉', '大荤');
INSERT INTO `foods` VALUES ('520', '清炖牛腩', '大荤');
INSERT INTO `foods` VALUES ('521', '红烧牛肉', '大荤');
INSERT INTO `foods` VALUES ('522', '萝卜牛腩', '大荤');
INSERT INTO `foods` VALUES ('523', '黄豆牛腩', '大荤');
INSERT INTO `foods` VALUES ('524', '蚝油牛肉', '大荤');
INSERT INTO `foods` VALUES ('525', '尖椒牛肉', '大荤');
INSERT INTO `foods` VALUES ('526', '芹菜牛肉丝', '大荤');
INSERT INTO `foods` VALUES ('527', '大葱牛肉', '大荤');
INSERT INTO `foods` VALUES ('528', '西芹牛肉', '大荤');
INSERT INTO `foods` VALUES ('529', '蒜苔牛肉丝', '大荤');
INSERT INTO `foods` VALUES ('530', '五彩牛肉丝', '大荤');
INSERT INTO `foods` VALUES ('531', '菜花牛肉', '大荤');
INSERT INTO `foods` VALUES ('532', '甜豆牛肉', '大荤');
INSERT INTO `foods` VALUES ('533', '青椒牛肉丝', '大荤');
INSERT INTO `foods` VALUES ('534', '水笋牛肉', '大荤');
INSERT INTO `foods` VALUES ('535', '青笋牛肉', '大荤');
INSERT INTO `foods` VALUES ('536', '青瓜牛肉', '大荤');
INSERT INTO `foods` VALUES ('537', '葱爆牛肉', '大荤');
INSERT INTO `foods` VALUES ('538', '咖喱牛肉', '大荤');
INSERT INTO `foods` VALUES ('539', '洋葱牛肉', '大荤');
INSERT INTO `foods` VALUES ('540', '鱼香牛肉丝', '大荤');
INSERT INTO `foods` VALUES ('541', '西芹牛肉', '大荤');
INSERT INTO `foods` VALUES ('542', '青椒牛肉', '大荤');
INSERT INTO `foods` VALUES ('543', '苦瓜牛肉', '大荤');
INSERT INTO `foods` VALUES ('544', '豆角牛肉', '大荤');
INSERT INTO `foods` VALUES ('545', '青瓜牛肉', '大荤');
INSERT INTO `foods` VALUES ('546', '红烧驴肉', '大荤');
INSERT INTO `foods` VALUES ('547', '五香驴肉', '大荤');
INSERT INTO `foods` VALUES ('548', '酱驴肉', '大荤');
INSERT INTO `foods` VALUES ('549', '麻辣驴肉', '大荤');
INSERT INTO `foods` VALUES ('550', '陈皮兔丁', '大荤');
INSERT INTO `foods` VALUES ('551', '红烧兔肉', '大荤');
INSERT INTO `foods` VALUES ('552', '红烧狗肉', '大荤');
INSERT INTO `foods` VALUES ('553', '腌炸鸡腿', '大荤');
INSERT INTO `foods` VALUES ('554', '炖乳鸽', '大荤');
INSERT INTO `foods` VALUES ('555', '瑶柱炖鸡', '大荤');
INSERT INTO `foods` VALUES ('556', '炖乌鸡', '大荤');
INSERT INTO `foods` VALUES ('557', '烤鸡', '大荤');
INSERT INTO `foods` VALUES ('558', '香辣鸡翅', '大荤');
INSERT INTO `foods` VALUES ('559', '冬菇蒸鸡', '大荤');
INSERT INTO `foods` VALUES ('560', '卤火鸡翅', '大荤');
INSERT INTO `foods` VALUES ('561', '辣子鸡块', '大荤');
INSERT INTO `foods` VALUES ('562', '香辣鸡珍', '大荤');
INSERT INTO `foods` VALUES ('563', '红油凤爪', '大荤');
INSERT INTO `foods` VALUES ('564', '麻辣鸡块', '大荤');
INSERT INTO `foods` VALUES ('565', '白切鸡', '大荤');
INSERT INTO `foods` VALUES ('566', '盐水鸡珍', '大荤');
INSERT INTO `foods` VALUES ('567', '红皮子鸡', '大荤');
INSERT INTO `foods` VALUES ('568', '椒盐鸡翅', '大荤');
INSERT INTO `foods` VALUES ('569', '香酥鸡', '大荤');
INSERT INTO `foods` VALUES ('570', '吉列鸡糕', '大荤');
INSERT INTO `foods` VALUES ('571', '怪味鸡丁', '大荤');
INSERT INTO `foods` VALUES ('572', '烧鹅', '大荤');
INSERT INTO `foods` VALUES ('573', '红油鸡翅', '大荤');
INSERT INTO `foods` VALUES ('574', '麻辣鸡翅', '大荤');
INSERT INTO `foods` VALUES ('575', '怪味鸡块', '大荤');
INSERT INTO `foods` VALUES ('576', '糖醋鸡柳', '大荤');
INSERT INTO `foods` VALUES ('577', '豉油鸡', '大荤');
INSERT INTO `foods` VALUES ('578', '小鸡炖蘑菇', '大荤');
INSERT INTO `foods` VALUES ('579', '蚝油凤爪', '大荤');
INSERT INTO `foods` VALUES ('580', '白云凤爪', '大荤');
INSERT INTO `foods` VALUES ('581', '卤鸡珍', '大荤');
INSERT INTO `foods` VALUES ('582', '子姜鸡片', '大荤');
INSERT INTO `foods` VALUES ('583', '双冬醋熘鸡', '大荤');
INSERT INTO `foods` VALUES ('584', '黑椒鸡柳', '大荤');
INSERT INTO `foods` VALUES ('585', '椒盐鸡柳', '大荤');
INSERT INTO `foods` VALUES ('586', '香酥鸭', '大荤');
INSERT INTO `foods` VALUES ('587', '绣球鸡丸', '大荤');
INSERT INTO `foods` VALUES ('588', '清汤鸡丸', '大荤');
INSERT INTO `foods` VALUES ('589', '烤鸡', '大荤');
INSERT INTO `foods` VALUES ('590', '酥炸鸡翅', '大荤');
INSERT INTO `foods` VALUES ('591', '红烧凤爪', '大荤');
INSERT INTO `foods` VALUES ('592', '尖椒鸡杂', '大荤');
INSERT INTO `foods` VALUES ('593', '鲜笋鸡片', '大荤');
INSERT INTO `foods` VALUES ('594', '韭菜花鸡丝', '大荤');
INSERT INTO `foods` VALUES ('595', '荷兰豆鸡片', '大荤');
INSERT INTO `foods` VALUES ('596', '菠萝鸡片', '大荤');
INSERT INTO `foods` VALUES ('597', '三色烩鱼丸', '大荤');
INSERT INTO `foods` VALUES ('598', '椒盐泥鳅', '大荤');
INSERT INTO `foods` VALUES ('599', '豉椒鳝片', '大荤');
INSERT INTO `foods` VALUES ('600', '红烧鲢鱼', '大荤');
INSERT INTO `foods` VALUES ('601', '豆瓣烧鱼', '大荤');
INSERT INTO `foods` VALUES ('602', '红烧鲫鱼', '大荤');
INSERT INTO `foods` VALUES ('603', '清蒸鲩鱼', '大荤');
INSERT INTO `foods` VALUES ('604', '酸菜焖鱼', '大荤');
INSERT INTO `foods` VALUES ('605', '红烧鱼块', '大荤');
INSERT INTO `foods` VALUES ('606', '红烧鲤鱼', '大荤');
INSERT INTO `foods` VALUES ('607', '油泡墨鱼丸', '大荤');
INSERT INTO `foods` VALUES ('608', '糖醋鱼块', '大荤');
INSERT INTO `foods` VALUES ('609', '红烧鲩鱼', '大荤');
INSERT INTO `foods` VALUES ('610', '酥炸鱼片', '大荤');
INSERT INTO `foods` VALUES ('611', '红烧鱼丸', '大荤');
INSERT INTO `foods` VALUES ('612', '豉汁蒸螗虱', '大荤');
INSERT INTO `foods` VALUES ('613', '醋熘鱼片', '大荤');
INSERT INTO `foods` VALUES ('614', '干煸鳝丝', '大荤');
INSERT INTO `foods` VALUES ('615', '吉列鱼片', '大荤');
INSERT INTO `foods` VALUES ('616', '酸菜鱼', '大荤');
INSERT INTO `foods` VALUES ('617', '红烧鳝鱼', '大荤');
INSERT INTO `foods` VALUES ('618', '豆腐鱼', '大荤');
INSERT INTO `foods` VALUES ('619', '清汤鱼丸', '大荤');
INSERT INTO `foods` VALUES ('620', '东坡鱼', '大荤');
INSERT INTO `foods` VALUES ('621', '清蒸鱼头', '大荤');
INSERT INTO `foods` VALUES ('622', '椒盐海虾', '大荤');
INSERT INTO `foods` VALUES ('623', '姜葱炒蟹', '大荤');
INSERT INTO `foods` VALUES ('624', '吉列炸虾', '大荤');
INSERT INTO `foods` VALUES ('625', '炖瑶柱', '大荤');
INSERT INTO `foods` VALUES ('626', '豉椒吹筒', '大荤');
INSERT INTO `foods` VALUES ('627', '糖醋爆虾', '大荤');
INSERT INTO `foods` VALUES ('628', '白灼吹筒', '大荤');
INSERT INTO `foods` VALUES ('629', '美极吹筒', '大荤');
INSERT INTO `foods` VALUES ('630', '糖醋菊花鱼', '大荤');
INSERT INTO `foods` VALUES ('631', '豉汁扣油缒', '大荤');
INSERT INTO `foods` VALUES ('632', '清蒸螃蟹', '大荤');
INSERT INTO `foods` VALUES ('633', '椒盐螃蟹', '大荤');
INSERT INTO `foods` VALUES ('634', '炒鱿鱼卷', '大荤');
INSERT INTO `foods` VALUES ('635', '吉列鳗鱼', '大荤');
INSERT INTO `foods` VALUES ('636', '清蒸仓鱼', '大荤');
INSERT INTO `foods` VALUES ('637', '五彩鲜鱿', '大荤');
INSERT INTO `foods` VALUES ('638', '豉椒炒青口', '大荤');
INSERT INTO `foods` VALUES ('639', '红烧佛手鱼', '大荤');
INSERT INTO `foods` VALUES ('640', '红烧黄花鱼', '大荤');
INSERT INTO `foods` VALUES ('641', '油泡鲜鱿', '大荤');
INSERT INTO `foods` VALUES ('642', '西芹鱿鱼', '大荤');
INSERT INTO `foods` VALUES ('643', '扣鳗鱼', '大荤');
INSERT INTO `foods` VALUES ('644', '蒜子扣白鳝', '大荤');
INSERT INTO `foods` VALUES ('645', '烧甫鱼', '大荤');
INSERT INTO `foods` VALUES ('646', '三丝烧红鱿', '大荤');
INSERT INTO `foods` VALUES ('647', '红烧海鱼', '大荤');
INSERT INTO `foods` VALUES ('648', '红烧鲳鱼', '大荤');
INSERT INTO `foods` VALUES ('649', '清蒸鱼干', '大荤');
INSERT INTO `foods` VALUES ('650', '豆豉泥猛', '大荤');
INSERT INTO `foods` VALUES ('651', '酥炸带鱼', '大荤');
INSERT INTO `foods` VALUES ('652', '酥炸沙丁鱼', '大荤');
INSERT INTO `foods` VALUES ('653', '脆炸黄花鱼', '大荤');
INSERT INTO `foods` VALUES ('654', '红烧泥猛', '大荤');
INSERT INTO `foods` VALUES ('655', '酥炸红珊鱼', '大荤');
INSERT INTO `foods` VALUES ('656', '酥炸仓鱼', '大荤');
INSERT INTO `foods` VALUES ('657', '干烧沙丁鱼', '大荤');
INSERT INTO `foods` VALUES ('658', '蒸红珊鱼', '大荤');
INSERT INTO `foods` VALUES ('659', '椒盐鱼干', '大荤');
INSERT INTO `foods` VALUES ('660', '红烧池鱼', '大荤');
INSERT INTO `foods` VALUES ('661', '豆椒鱼干', '大荤');
INSERT INTO `foods` VALUES ('662', '烧马胶鱼', '大荤');
INSERT INTO `foods` VALUES ('663', '椒盐黄花鱼', '大荤');
INSERT INTO `foods` VALUES ('664', '豆豉鲮鱼', '大荤');
INSERT INTO `foods` VALUES ('665', '椒盐泥猛', '大荤');
INSERT INTO `foods` VALUES ('666', '椒盐沙丁鱼', '大荤');
INSERT INTO `foods` VALUES ('667', '酥炸海鱼', '大荤');
INSERT INTO `foods` VALUES ('668', '酥炸刀鱼', '大荤');
INSERT INTO `foods` VALUES ('669', '糖醋带鱼', '大荤');
INSERT INTO `foods` VALUES ('670', '炸鱼干', '大荤');
INSERT INTO `foods` VALUES ('671', '炸咸鱼', '大荤');
INSERT INTO `foods` VALUES ('672', '蒸咸鱼', '大荤');
INSERT INTO `foods` VALUES ('673', '煎荷包蛋', '大荤');
INSERT INTO `foods` VALUES ('674', '肉茸蛋盅', '大荤');
INSERT INTO `foods` VALUES ('675', '三文治炒蛋', '大荤');
INSERT INTO `foods` VALUES ('676', '尖椒拌皮蛋', '大荤');
INSERT INTO `foods` VALUES ('677', '蒸水蛋', '大荤');
INSERT INTO `foods` VALUES ('678', '茶叶蛋', '大荤');
INSERT INTO `foods` VALUES ('679', '拌皮蛋', '大荤');
INSERT INTO `foods` VALUES ('680', '三丝蛋卷', '大荤');
INSERT INTO `foods` VALUES ('681', '青椒回锅肉', '小荤');
INSERT INTO `foods` VALUES ('682', '宫爆肉丁', '小荤');
INSERT INTO `foods` VALUES ('683', '大骨烧黄豆', '小荤');
INSERT INTO `foods` VALUES ('684', '鲜笋炒肉', '小荤');
INSERT INTO `foods` VALUES ('685', '五花肉炖海带', '小荤');
INSERT INTO `foods` VALUES ('686', '碎米肉丁', '小荤');
INSERT INTO `foods` VALUES ('687', '青瓜肉片', '小荤');
INSERT INTO `foods` VALUES ('688', '肉末煸豆角', '小荤');
INSERT INTO `foods` VALUES ('689', '土豆肉丝', '小荤');
INSERT INTO `foods` VALUES ('690', '豆角肉片', '小荤');
INSERT INTO `foods` VALUES ('691', '豆干肉丝', '小荤');
INSERT INTO `foods` VALUES ('692', '香辣肉丁', '小荤');
INSERT INTO `foods` VALUES ('693', '木耳肉片', '小荤');
INSERT INTO `foods` VALUES ('694', '鱼香肉丝', '小荤');
INSERT INTO `foods` VALUES ('695', '豆角肉丝', '小荤');
INSERT INTO `foods` VALUES ('696', '菜胆肉片', '小荤');
INSERT INTO `foods` VALUES ('697', '青椒肉丝', '小荤');
INSERT INTO `foods` VALUES ('698', '青瓜木耳火腿', '小荤');
INSERT INTO `foods` VALUES ('699', '莲藕肉片', '小荤');
INSERT INTO `foods` VALUES ('700', '西芹肉片', '小荤');
INSERT INTO `foods` VALUES ('701', '芹菜肉片', '小荤');
INSERT INTO `foods` VALUES ('702', '菜胆回锅肉', '小荤');
INSERT INTO `foods` VALUES ('703', '玉豆回锅肉', '小荤');
INSERT INTO `foods` VALUES ('704', '菜花回锅肉', '小荤');
INSERT INTO `foods` VALUES ('705', '豆角回锅肉', '小荤');
INSERT INTO `foods` VALUES ('706', '大葱肉片', '小荤');
INSERT INTO `foods` VALUES ('707', '佛手瓜肉片', '小荤');
INSERT INTO `foods` VALUES ('708', '豆干回锅肉', '小荤');
INSERT INTO `foods` VALUES ('709', '菜头回锅肉', '小荤');
INSERT INTO `foods` VALUES ('710', '腐竹肉片', '小荤');
INSERT INTO `foods` VALUES ('711', '白菜梗肉片', '小荤');
INSERT INTO `foods` VALUES ('712', '西芹莲藕肉丁', '小荤');
INSERT INTO `foods` VALUES ('713', '高笋肉片', '小荤');
INSERT INTO `foods` VALUES ('714', '青瓜回锅肉', '小荤');
INSERT INTO `foods` VALUES ('715', '红萝卜回锅肉', '小荤');
INSERT INTO `foods` VALUES ('716', '玉豆回锅肉', '小荤');
INSERT INTO `foods` VALUES ('717', '尖椒肉片', '小荤');
INSERT INTO `foods` VALUES ('718', '蒜苔肉丝', '小荤');
INSERT INTO `foods` VALUES ('719', '蒜苔回锅肉', '小荤');
INSERT INTO `foods` VALUES ('720', '蒜苔肉丁', '小荤');
INSERT INTO `foods` VALUES ('721', '土豆肉片', '小荤');
INSERT INTO `foods` VALUES ('722', '青笋肉丝', '小荤');
INSERT INTO `foods` VALUES ('723', '水笋肉片', '小荤');
INSERT INTO `foods` VALUES ('724', '五彩肉丝', '小荤');
INSERT INTO `foods` VALUES ('725', '青豆玉米肉丁', '小荤');
INSERT INTO `foods` VALUES ('726', '咸菜肉丝', '小荤');
INSERT INTO `foods` VALUES ('727', '蒜苔火腿丝', '小荤');
INSERT INTO `foods` VALUES ('728', '芹菜肉丝', '小荤');
INSERT INTO `foods` VALUES ('729', '萝卜大骨', '小荤');
INSERT INTO `foods` VALUES ('730', '酸菜白肉粉条', '小荤');
INSERT INTO `foods` VALUES ('731', '肉茸腐竹', '小荤');
INSERT INTO `foods` VALUES ('732', '家常豆腐', '小荤');
INSERT INTO `foods` VALUES ('733', '麻婆豆腐', '小荤');
INSERT INTO `foods` VALUES ('734', '熊掌豆腐', '小荤');
INSERT INTO `foods` VALUES ('735', '肉末酸豆角', '小荤');

-- ----------------------------
-- Table structure for `likelist`
-- ----------------------------
DROP TABLE IF EXISTS `likelist`;
CREATE TABLE `likelist` (
  `Lid` int(11) NOT NULL AUTO_INCREMENT,
  `Uid` int(11) DEFAULT NULL,
  `Fid` int(11) DEFAULT NULL,
  PRIMARY KEY (`Lid`),
  KEY `Uid` (`Uid`),
  KEY `Fid` (`Fid`),
  CONSTRAINT `likelist_ibfk_1` FOREIGN KEY (`Uid`) REFERENCES `users` (`Uid`) ON DELETE CASCADE,
  CONSTRAINT `likelist_ibfk_2` FOREIGN KEY (`Fid`) REFERENCES `foods` (`Fid`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of likelist
-- ----------------------------
INSERT INTO `likelist` VALUES ('3', '2', '3');
INSERT INTO `likelist` VALUES ('4', '2', '5');
INSERT INTO `likelist` VALUES ('5', '2', '23');
INSERT INTO `likelist` VALUES ('6', '3', '5');
INSERT INTO `likelist` VALUES ('7', '1', '428');
INSERT INTO `likelist` VALUES ('8', '1', '93');

-- ----------------------------
-- Table structure for `users`
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `Uid` int(11) NOT NULL AUTO_INCREMENT,
  `Username` varchar(20) DEFAULT NULL,
  `Password` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`Uid`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of users
-- ----------------------------
INSERT INTO `users` VALUES ('1', 'dengtianyue', '123456');
INSERT INTO `users` VALUES ('2', 'qingqing', '123456');
INSERT INTO `users` VALUES ('3', 'deng', '123456');
INSERT INTO `users` VALUES ('4', 'hahaha', '123456');
INSERT INTO `users` VALUES ('5', 'lolol', '123456');
